# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
script:
- set -o pipefail && xcodebuild test -workspace Example/RxExample/Moya-SwiftyJSONMapper.xcworkspace -scheme Moya-SwiftyJSONMapper-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -workspace Example/RACExample/Moya-SwiftyJSONMapper.xcworkspace -scheme Moya-SwiftyJSONMapper-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --quick
- TEST_CMD="xcodebuild -scheme MoyaSwiftyJSONMapper -project MoyaSwiftyJSONMapper.xcodeproj  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S' build test" | xcpretty  && exit ${PIPESTATUS[0]}
after_success:
  - bash <(curl -s https://codecov.io/bash)
